#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 23 09:36:12 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'sample'
    mvnCommands = '--version'
    test='false'
}